# Generated by Django 2.1.5 on 2021-08-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
