# Generated by Django 2.1.5 on 2021-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLiked',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Web liked',
                'verbose_name_plural': 'Web liked',
            },
        ),
    ]
