# Generated by Django 2.1.5 on 2021-08-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_websiteliked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteliked',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
